try:
    print(y)
except:
    print("An exception occurred")